export const FormTypes = {
    SET_MAIN_OBJECT: 'SET_MAIN_OBJECT',
    SEND_POST_REQUEST: 'SEND_POST_REQUEST',
    POST_REQUEST_SUCCESS: 'POST_REQUEST_SUCCESS',
    POST_REQUEST_FAIL: 'POST_REQUEST_SUCCESS',
};
