export const laptopInfoTypes = {
    SET_IMAGE_INPUT_DRAG_ENTER: 'SET_IMAGE_INPUT_DRAG_ENTER ',
    SET_LAPTOP_FORM_OBJECT: 'SET_LAPTOP_FORM_OBJECT',
    SET_FORM_ERRORS: 'SET_FORM_ERRORS',
    SET_FETCHED_DATA: 'SET_FETCHED_DATA',
    SET_CURR_DATA: 'SET_CURR_DATA',
    SET_ACTIVE_NAMES: 'SET_ACTIVE_NAMES',
    REHYDRATE_STATE: 'REHYDRATE_STATE',
};
