export const formTypes = {
    SET_MAIN_OBJECT: 'form/SET_MAIN_OBJECT',
    SEND_POST_REQUEST: 'form/SEND_POST_REQUEST',
    POST_REQUEST_SUCCESS: 'form/POST_REQUEST_SUCCESS',
    POST_REQUEST_FAIL: 'form/POST_REQUEST_SUCCESS',
    SET_DEFAULT: 'form/SET_DEFAULT',
};
